<?php

namespace TestBundle\Repository;

/**
 * table5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class table5Repository extends \Doctrine\ORM\EntityRepository
{
}
