<?php

namespace TestBundle\Repository;

/**
 * table4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class table4Repository extends \Doctrine\ORM\EntityRepository
{
}
